<?php
/* Originally from Icinga Web 2 Reporting Module (c) Icinga GmbH | GPLv2+ */

/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Clustergraph\Forms;

use Icinga\Data\ResourceFactory;
use Icinga\Forms\ConfigForm;

class ModuleconfigForm extends ConfigForm
{

    protected static $dummyPassword = '_web_form_m0r34m4z1n6n1ck';


    public function init()
    {

        $this->setName('clustergraph_settings');
        $this->setSubmitLabel($this->translate('Save Changes'));
    }

    public function createElements(array $formData)
    {
        $this->addElement('text', 'api_user', [
            'label' => 'API User',
            'description' => 'Add a user in api-users.conf with these permissions:  permissions = [ "objects/query/Zone", "objects/query/Endpoint" ]',
            'required' => true,
        ]);

        $this->addElement('password', 'api_password', [
            'label' => 'API Password',
            'autocomplete' => 'new-password',
            'required' => true,
            'renderPassword' => true
        ]);

        $this->addElement('text', 'api_endpoint', [
            'label' => 'API Endpoint',
            'description' => 'Example: https://myicingamaster.mydomain:5665/v1',
            'required' => true,
        ]);

        $this->addElement('checkbox', 'api_verify', [
            'label' => 'Enable SSL Verification',
            'description' => 'If checked, SSL verification will be enabled.',
            'value' => 0,
        ]);
    }

    public function onRequest()
    {
        parent::onRequest();
        foreach ($this->getElements() as $element) {
            if ($element->getType() === 'Zend_Form_Element_Password' && strlen($element->getValue())) {
                $element->setValue(static::$dummyPassword);
            }
        }
    }

    /**
     * {@inheritdoc}
     */
    public function getValues($suppressArrayNotation = false)
    {
        $values = parent::getValues($suppressArrayNotation);
        $resource = "api";
        if ($resource !== null && $this->config->hasSection($resource)) {

            $resourceConfig = $this->config->getSection($resource)->toArray();

            foreach ($this->getElements() as $element) {
                if ($element->getType() === 'Zend_Form_Element_Password') {
                    $name = $element->getName();
                    $name2 = str_replace($resource . "_", "", $name);

                    if (isset($values[$name]) && $values[$name] === static::$dummyPassword) {
                        if (isset($resourceConfig[$name2])) {
                            $values[$name] = $resourceConfig[$name2];
                        } else {
                            unset($values[$name]);
                        }

                    }
                }
            }
        }

        return $values;
    }

}