<?php if (isset($this->successMessage)): ?>
    <div class="success">
        <?= $this->successMessage ?>
    </div>
<?php endif; ?>


<div class="section">
    <h2><?= $this->translate('Cluster Graph Configuration') ?></h2>
    <p>
        Enter the config details for an API user with the required permissions to read the Zones and Endpoints from your master node. Example permissions:
        <pre>

object ApiUser "CLUSTERGRAPH_USERNAME_HERE" {
  password = "SECURE_PASSWORD_HERE"

  permissions = [ "objects/query/Zone", "objects/query/Endpoint" ]
}

        </pre>
    </p>
    <?= $this->form ?>
</div>

