<?php if (!$this->compact): ?>
    <div class="controls">
        <?= $this->tabs ?>
    </div>
<?php endif ?>
<div class="content">
    <p>
        Enter the config details for an API user with the required permissions to read the Zones and Endpoints from your
        master node. Example permissions:
    <pre>

object ApiUser "CLUSTERGRAPH_USERNAME_HERE" {
  password = "SECURE_PASSWORD_HERE"

  permissions = [ "objects/query/Zone", "objects/query/Endpoint" ]
}

        </pre>
    </p>
    <?= $this->form ?>
</div>


